#!/usr/bin/env python3
"""Create the local DuckDB analytical database for SQL answer generation."""

from __future__ import annotations

import argparse
import hashlib
import json
import os
import sys
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parents[2]
PROJECT_PACKAGES = ROOT / ".python_packages"
if PROJECT_PACKAGES.exists():
    sys.path.insert(0, str(PROJECT_PACKAGES))

import duckdb  # type: ignore  # noqa: E402
import pandas as pd  # noqa: E402


SQL_ROOT = ROOT / "sql_database"
DEFAULT_DB_PATH = SQL_ROOT / "db" / "semantics.duckdb"
DOCS_DIR = SQL_ROOT / "docs"
RAW_DIR = ROOT / "data" / "raw"
OUTPUTS_DIR = ROOT / "outputs"
KG_DIR = ROOT / "artifacts" / "kg"


DERIVED_MKN_BLOCKS: list[tuple[str, str, str]] = [
    ("A00", "A09", "Střevní infekční nemoci"),
    ("A20", "A28", "Některé bakteriální zoonózy"),
    ("A30", "A49", "Jiné bakteriální nemoci"),
    ("A50", "A64", "Infekce přenášené převážně pohlavním stykem"),
    ("A65", "A69", "Jiné spirochetové nemoci"),
    ("A70", "A74", "Jiné nemoci způsobené chlamydiemi"),
    ("A75", "A79", "Rickettsiózy"),
    ("A80", "A89", "Virové infekce centrální nervové soustavy"),
    ("A92", "A99", "Virové horečky a virové hemoragické horečky přenášené členovci"),
    ("B00", "B09", "Virové infekce charakterizované postižením kůže a sliznice"),
    ("B15", "B19", "Virová hepatitida"),
    ("B25", "B34", "Jiné virové nemoci"),
    ("B35", "B49", "Mykózy"),
    ("B50", "B64", "Protozoární nemoci"),
    ("B65", "B83", "Helmintózy - hlístové nemoci"),
    ("B85", "B89", "Zavšivení, akarióza a jiná napadení"),
    ("B95", "B98", "Bakteriální, virová a jiná infekční agens"),
    ("B99", "B99", "Jiné infekční nemoci"),
    ("G00", "G09", "Zánětlivé nemoci centrální nervové soustavy"),
    ("G50", "G59", "Onemocnění nervů, nervových kořenů a pletení"),
    ("G60", "G64", "Polyneuropatie a jiné nemoci periferní nervové soustavy"),
    ("J00", "J06", "Akutní infekce horních dýchacích cest"),
    ("J09", "J18", "Chřipka a zánět plic (pneumonie)"),
    ("W50", "W64", "Vystavení životným mechanickým silám"),
]

BLOCK_SOURCE = "derived_from_configured_MKN10_block_ranges; source_CSV_has_no_explicit_block_column"
SEX_LABELS_CS = {"M": "muž", "Z": "žena"}


FINAL_TABLE_NAME = "fact_infectious_disease_cases_enriched"

FINAL_TABLE_COLUMNS: list[dict[str, str]] = [
    {
        "column": "fact_id",
        "type": "BIGINT",
        "description": "Stable surrogate key for one row in the final analytical fact table. It follows the source infectious-disease CSV row order.",
        "source": "Generated by the SQL builder from source row order.",
        "usage": "Use only as a row identifier; do not aggregate it as a health measure.",
    },
    {
        "column": "source_dataset",
        "type": "VARCHAR",
        "description": "Name of the source fact dataset. For this final table the value is always infectious_diseases.",
        "source": "Generated constant.",
        "usage": "Useful when a future backend exposes several fact tables.",
    },
    {
        "column": "source_row_id",
        "type": "BIGINT",
        "description": "One-based row number from data/raw/infectious_diseases.csv.",
        "source": "Generated from source CSV row order.",
        "usage": "Traceability back to the raw source table.",
    },
    {
        "column": "report_year",
        "type": "INTEGER",
        "description": "Year when the infectious-disease case was reported.",
        "source": "infectious_diseases.rok",
        "usage": "Filter or group by year. The loaded source spans 2018-2025.",
    },
    {
        "column": "report_month",
        "type": "INTEGER",
        "description": "Month when the infectious-disease case was reported, encoded as 1-12.",
        "source": "infectious_diseases.mesic",
        "usage": "Filter or group by month for seasonality-style questions.",
    },
    {
        "column": "period_yyyymm",
        "type": "INTEGER",
        "description": "Compact year-month key in YYYYMM form.",
        "source": "Derived as report_year * 100 + report_month.",
        "usage": "Sort or filter month-level periods without building dates.",
    },
    {
        "column": "date_grain",
        "type": "VARCHAR",
        "description": "Temporal grain of the source fact row. The value is always month.",
        "source": "Generated constant.",
        "usage": "Helps downstream code avoid treating the table as daily or patient-level data.",
    },
    {
        "column": "region_code",
        "type": "VARCHAR",
        "description": "Official Czech regional code for the reporting region.",
        "source": "infectious_diseases.kraj_kod",
        "usage": "Use for exact region filters such as CZ010 for Prague.",
    },
    {
        "column": "region_name_cs",
        "type": "VARCHAR",
        "description": "Official Czech region label.",
        "source": "infectious_diseases.kraj_nazev",
        "usage": "Display label for grouped regional answers.",
    },
    {
        "column": "diagnosis_code",
        "type": "VARCHAR",
        "description": "Three-character diagnosis code reported in the infectious-disease table.",
        "source": "infectious_diseases.diagnoza",
        "usage": "Primary disease filter value. KG-RAG should expand disease-family concepts to this column before aggregation.",
    },
    {
        "column": "diagnosis_name_cs",
        "type": "VARCHAR",
        "description": "Czech diagnosis label as used in the infectious-disease table.",
        "source": "infectious_diseases.diagnoza_nazev",
        "usage": "Display label beside diagnosis_code in final answer tables.",
    },
    {
        "column": "mkn_code",
        "type": "VARCHAR",
        "description": "Matching MKN-10-CZ code from the official code list.",
        "source": "mkn10_cz.kod matched by diagnosis_code.",
        "usage": "Trace the fact diagnosis to the official MKN-10-CZ code list.",
    },
    {
        "column": "mkn_code_with_dot",
        "type": "VARCHAR",
        "description": "MKN-10-CZ dotted code form, if different from the plain code.",
        "source": "mkn10_cz.kod_tecka.",
        "usage": "Useful when displaying official code-list values.",
    },
    {
        "column": "mkn_name_cs",
        "type": "VARCHAR",
        "description": "Official Czech MKN-10-CZ diagnosis label.",
        "source": "mkn10_cz.nazev.",
        "usage": "Use for terminology checks against diagnosis_name_cs.",
    },
    {
        "column": "mkn_iri",
        "type": "VARCHAR",
        "description": "Official IRI for the MKN-10-CZ code.",
        "source": "mkn10_cz.kod_IRI.",
        "usage": "Semantic traceability link for KG/entity answers.",
    },
    {
        "column": "mkn_block_code",
        "type": "VARCHAR",
        "description": "Derived MKN-10 block/range containing the diagnosis code, such as A00-A09.",
        "source": "Derived from configured MKN-10 block ranges because the source CSV has chapters but no explicit block column.",
        "usage": "Main KG-RAG expansion column for disease-family queries.",
    },
    {
        "column": "mkn_block_name_cs",
        "type": "VARCHAR",
        "description": "Czech label for the derived MKN-10 block.",
        "source": "Configured derived block ranges.",
        "usage": "Display or filter disease-family scopes such as Střevní infekční nemoci.",
    },
    {
        "column": "mkn_block_source",
        "type": "VARCHAR",
        "description": "Provenance note for the block assignment.",
        "source": "Generated constant for derived block assignments.",
        "usage": "Documents that MKN block is derived, not directly present in the source CSV.",
    },
    {
        "column": "mkn_chapter_range",
        "type": "VARCHAR",
        "description": "MKN-10-CZ chapter code range, for example A00-B99.",
        "source": "mkn10_cz.kod_kapitola_rozsah.",
        "usage": "Higher-level grouping above block.",
    },
    {
        "column": "mkn_chapter_number",
        "type": "VARCHAR",
        "description": "MKN-10-CZ chapter number, for example I.",
        "source": "mkn10_cz.kod_kapitola_cislo.",
        "usage": "Display chapter identifiers.",
    },
    {
        "column": "mkn_chapter_name_cs",
        "type": "VARCHAR",
        "description": "Czech MKN-10-CZ chapter label.",
        "source": "mkn10_cz.nazev_kapitola.",
        "usage": "Display higher-level disease category context.",
    },
    {
        "column": "has_mkn_match",
        "type": "BOOLEAN",
        "description": "True when diagnosis_code matched the official MKN-10-CZ code list.",
        "source": "Derived from the join to mkn10_cz.",
        "usage": "Quality-control filter. It should be true for all current infectious-disease diagnosis values.",
    },
    {
        "column": "age_group_code",
        "type": "VARCHAR",
        "description": "Official NZIS age-group code.",
        "source": "infectious_diseases.vek_kod.",
        "usage": "Exact age-group filtering and grouping.",
    },
    {
        "column": "age_group_name_cs",
        "type": "VARCHAR",
        "description": "Czech age-group label used in the infectious-disease table.",
        "source": "infectious_diseases.vek_nazev.",
        "usage": "Display label for grouped age answers.",
    },
    {
        "column": "age_from_inclusive",
        "type": "INTEGER",
        "description": "Lower bound of the age group, inclusive.",
        "source": "age_groups.vek_od_vcetne joined by age_group_code.",
        "usage": "Normalize informal age concepts such as children or seniors 65+.",
    },
    {
        "column": "age_to_inclusive",
        "type": "INTEGER",
        "description": "Upper bound of the age group, inclusive. The open-ended 75+ group uses the source code-list upper bound.",
        "source": "age_groups.vek_do_vcetne joined by age_group_code.",
        "usage": "Normalize interval questions and sort age groups.",
    },
    {
        "column": "has_age_group_match",
        "type": "BOOLEAN",
        "description": "True when age_group_code matched the official NZIS age-group code list.",
        "source": "Derived from the join to age_groups.",
        "usage": "Quality-control filter.",
    },
    {
        "column": "sex_code",
        "type": "VARCHAR",
        "description": "Sex category from the source table. M = muž, Z = žena.",
        "source": "infectious_diseases.pohlavi.",
        "usage": "Filter or group by sex when needed.",
    },
    {
        "column": "sex_name_cs",
        "type": "VARCHAR",
        "description": "Czech display label for sex_code.",
        "source": "Derived from sex_code.",
        "usage": "Display label in final answers.",
    },
    {
        "column": "ews_code",
        "type": "INTEGER",
        "description": "EWS value from the infectious-disease source table. It is retained as a source dimension/code, not interpreted clinically by this project.",
        "source": "infectious_diseases.EWS.",
        "usage": "Use only if a future question explicitly needs this source field.",
    },
    {
        "column": "reported_case_count",
        "type": "BIGINT",
        "description": "Reported case-count measure for the aggregate row.",
        "source": "infectious_diseases.pocet_pripadu.",
        "usage": "Main measure to sum in answer SQL. Do not describe it as unique patients or incidence.",
    },
]


def now_iso() -> str:
    return datetime.now(timezone.utc).replace(microsecond=0).isoformat()


def log(message: str) -> None:
    print(f"[{datetime.now(timezone.utc).strftime('%H:%M:%S')} UTC] {message}", flush=True)


def file_sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for chunk in iter(lambda: handle.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def code_rank(code: str) -> int | None:
    code = str(code).strip().upper()
    if len(code) < 3 or not code[0].isalpha() or not code[1:3].isdigit():
        return None
    return (ord(code[0]) - ord("A")) * 1000 + int(code[1:3])


def block_for_code(code: str) -> tuple[str, str, str] | None:
    rank = code_rank(code)
    if rank is None:
        return None
    for start, end, label in DERIVED_MKN_BLOCKS:
        start_rank = code_rank(start)
        end_rank = code_rank(end)
        if start_rank is not None and end_rank is not None and start_rank <= rank <= end_rank:
            return f"{start}-{end}", label, BLOCK_SOURCE
    return None


def read_csvs() -> dict[str, pd.DataFrame]:
    log("Loading complete raw CSV files")
    return {
        "infectious": pd.read_csv(
            RAW_DIR / "infectious_diseases.csv",
            encoding="utf-8-sig",
            low_memory=False,
            dtype={"kraj_kod": "string", "diagnoza": "string", "vek_kod": "string", "pohlavi": "string"},
        ),
        "age_groups": pd.read_csv(
            RAW_DIR / "age_groups.csv",
            encoding="utf-8-sig",
            low_memory=False,
            dtype={"vek_kod": "string", "ciselnik_kod": "string"},
        ),
        "mkn10": pd.read_csv(
            RAW_DIR / "mkn10_cz.csv",
            encoding="utf-8-sig",
            low_memory=False,
            dtype={"kod": "string", "kod_tecka": "string"},
        ),
        "hospitalization": pd.read_csv(
            RAW_DIR / "hospitalization.csv",
            encoding="utf-8-sig",
            low_memory=False,
            dtype={"vek_kod": "string", "kraj_pacient": "string", "ZDG": "string"},
        ),
    }


def build_block_dimension() -> pd.DataFrame:
    rows = []
    for start, end, label in DERIVED_MKN_BLOCKS:
        rows.append(
            {
                "mkn_block_code": f"{start}-{end}",
                "mkn_block_start_code": start,
                "mkn_block_end_code": end,
                "mkn_block_start_rank": code_rank(start),
                "mkn_block_end_rank": code_rank(end),
                "mkn_block_name_cs": label,
                "mkn_block_source": BLOCK_SOURCE,
            }
        )
    return pd.DataFrame(rows)


def build_mkn_dimension(mkn10: pd.DataFrame) -> pd.DataFrame:
    log("Building enriched MKN-10-CZ dimension")
    mkn = mkn10.drop_duplicates("kod").copy()
    block_records = mkn["kod"].map(lambda value: block_for_code(str(value)))
    return pd.DataFrame(
        {
            "mkn_code": mkn["kod"].astype("string"),
            "mkn_code_with_dot": mkn["kod_tecka"].astype("string"),
            "mkn_name_cs": mkn["nazev"].astype("string"),
            "mkn_iri": mkn["kod_IRI"].astype("string"),
            "mkn_chapter_range": mkn["kod_kapitola_rozsah"].astype("string"),
            "mkn_chapter_number": mkn["kod_kapitola_cislo"].astype("string"),
            "mkn_chapter_name_cs": mkn["nazev_kapitola"].astype("string"),
            "mkn_valid_from": mkn["platnost_od"].astype("string"),
            "mkn_valid_to": mkn["platnost_do"].astype("string"),
            "mkn_block_code": block_records.map(lambda item: item[0] if item else None).astype("string"),
            "mkn_block_name_cs": block_records.map(lambda item: item[1] if item else None).astype("string"),
            "mkn_block_source": block_records.map(lambda item: item[2] if item else None).astype("string"),
        }
    )


def build_age_dimension(age_groups: pd.DataFrame) -> pd.DataFrame:
    log("Building age-group dimension")
    age = age_groups.drop_duplicates("vek_kod").copy()
    return pd.DataFrame(
        {
            "age_group_code": age["vek_kod"].astype("string"),
            "age_group_name_cs": age["vek_nazev"].astype("string"),
            "age_iri": age["vek_IRI"].astype("string"),
            "age_from_inclusive": pd.to_numeric(age["vek_od_vcetne"], errors="coerce").astype("Int64"),
            "age_to_inclusive": pd.to_numeric(age["vek_do_vcetne"], errors="coerce").astype("Int64"),
        }
    )


def build_region_dimension(infectious: pd.DataFrame) -> pd.DataFrame:
    log("Building region dimension")
    regions = infectious[["kraj_kod", "kraj_nazev"]].drop_duplicates().copy()
    regions["region_code"] = regions["kraj_kod"].astype("string")
    regions["region_name_cs"] = regions["kraj_nazev"].astype("string")
    return regions[["region_code", "region_name_cs"]]


def build_final_fact(infectious: pd.DataFrame, dim_mkn: pd.DataFrame, dim_age: pd.DataFrame) -> pd.DataFrame:
    log("Building final enriched infectious-disease fact table")
    fact = infectious.copy()
    fact.insert(0, "source_row_id", range(1, len(fact) + 1))
    fact["fact_id"] = fact["source_row_id"]
    fact["source_dataset"] = "infectious_diseases"
    fact["report_year"] = pd.to_numeric(fact["rok"], errors="coerce").astype("Int64")
    fact["report_month"] = pd.to_numeric(fact["mesic"], errors="coerce").astype("Int64")
    fact["period_yyyymm"] = fact["report_year"] * 100 + fact["report_month"]
    fact["date_grain"] = "month"
    fact["region_code"] = fact["kraj_kod"].astype("string")
    fact["region_name_cs"] = fact["kraj_nazev"].astype("string")
    fact["diagnosis_code"] = fact["diagnoza"].astype("string")
    fact["diagnosis_name_cs"] = fact["diagnoza_nazev"].astype("string")
    fact["age_group_code"] = fact["vek_kod"].astype("string")
    fact["age_group_name_cs"] = fact["vek_nazev"].astype("string")
    fact["sex_code"] = fact["pohlavi"].astype("string")
    fact["sex_name_cs"] = fact["sex_code"].map(SEX_LABELS_CS).astype("string")
    fact["ews_code"] = pd.to_numeric(fact["EWS"], errors="coerce").astype("Int64")
    fact["reported_case_count"] = pd.to_numeric(fact["pocet_pripadu"], errors="coerce").fillna(0).astype("int64")

    fact = fact.merge(dim_mkn, left_on="diagnosis_code", right_on="mkn_code", how="left")
    fact = fact.merge(dim_age, on="age_group_code", how="left", suffixes=("", "_official"))
    fact["has_mkn_match"] = fact["mkn_code"].notna()
    fact["has_age_group_match"] = fact["age_from_inclusive"].notna()

    ordered_columns = [column["column"] for column in FINAL_TABLE_COLUMNS]
    return fact[ordered_columns]


def load_kg_nodes() -> pd.DataFrame:
    path = KG_DIR / "nodes.jsonl"
    if not path.exists():
        return pd.DataFrame(columns=["node_id", "node_type", "node_label", "aliases_json", "properties_json"])
    rows = []
    with path.open("r", encoding="utf-8") as handle:
        for line in handle:
            if not line.strip():
                continue
            record = json.loads(line)
            rows.append(
                {
                    "node_id": record.get("id"),
                    "node_type": record.get("type"),
                    "node_label": record.get("label"),
                    "aliases_json": json.dumps(record.get("aliases", []), ensure_ascii=False),
                    "properties_json": json.dumps(record.get("properties", {}), ensure_ascii=False),
                }
            )
    return pd.DataFrame(rows)


def load_kg_edges() -> pd.DataFrame:
    path = KG_DIR / "edges.jsonl"
    if not path.exists():
        return pd.DataFrame(columns=["source_node_id", "target_node_id", "edge_type", "properties_json"])
    rows = []
    with path.open("r", encoding="utf-8") as handle:
        for line in handle:
            if not line.strip():
                continue
            record = json.loads(line)
            rows.append(
                {
                    "source_node_id": record.get("source"),
                    "target_node_id": record.get("target"),
                    "edge_type": record.get("type"),
                    "properties_json": json.dumps(record.get("properties", {}), ensure_ascii=False),
                }
            )
    return pd.DataFrame(rows)


def load_evaluation_tables() -> dict[str, pd.DataFrame]:
    path = OUTPUTS_DIR / "kg_rag_evaluation_queries.json"
    if not path.exists():
        return {
            "evaluation_question": pd.DataFrame(),
            "evaluation_scope_diagnosis_code": pd.DataFrame(),
            "evaluation_scope_absent_mkn_code": pd.DataFrame(),
            "evaluation_scope_age_group": pd.DataFrame(),
            "evaluation_scope_region": pd.DataFrame(),
            "evaluation_scope_year": pd.DataFrame(),
        }
    records = json.loads(path.read_text(encoding="utf-8"))
    question_rows = []
    diagnosis_rows = []
    absent_rows = []
    age_rows = []
    region_rows = []
    year_rows = []
    for item in records:
        qid = item["id"]
        scope = item.get("gold_scope") or {}
        question_rows.append(
            {
                "evaluation_id": qid,
                "query_cs": item.get("query_cs"),
                "query_en": item.get("query_en"),
                "intent": item.get("intent"),
                "primary_metric": item.get("primary_metric"),
                "expected_sql_shape": item.get("expected_sql_shape"),
                "mkn_group": scope.get("mkn_group"),
            }
        )
        for code in scope.get("diagnosis_codes", []):
            diagnosis_rows.append({"evaluation_id": qid, "diagnosis_code": code})
        for code in scope.get("mkn_relevant_absent_codes", []):
            absent_rows.append({"evaluation_id": qid, "mkn_code": code})
        for code in scope.get("age_groups", []):
            age_rows.append({"evaluation_id": qid, "age_group_code": str(code)})
        for region in scope.get("regions", []):
            region_rows.append({"evaluation_id": qid, "region_name_cs": region})
        if scope.get("region_code") or scope.get("region_label"):
            region_rows.append(
                {
                    "evaluation_id": qid,
                    "region_code": scope.get("region_code"),
                    "region_name_cs": scope.get("region_label"),
                }
            )
        for year in scope.get("years", []):
            year_rows.append({"evaluation_id": qid, "report_year": int(year)})
    return {
        "evaluation_question": pd.DataFrame(question_rows),
        "evaluation_scope_diagnosis_code": pd.DataFrame(diagnosis_rows),
        "evaluation_scope_absent_mkn_code": pd.DataFrame(absent_rows),
        "evaluation_scope_age_group": pd.DataFrame(age_rows),
        "evaluation_scope_region": pd.DataFrame(region_rows),
        "evaluation_scope_year": pd.DataFrame(year_rows),
    }


def write_docs(final_table: pd.DataFrame) -> None:
    DOCS_DIR.mkdir(parents=True, exist_ok=True)
    (DOCS_DIR / "final_table_columns.json").write_text(
        json.dumps(FINAL_TABLE_COLUMNS, ensure_ascii=False, indent=2) + "\n",
        encoding="utf-8",
    )
    pd.DataFrame(FINAL_TABLE_COLUMNS).to_csv(DOCS_DIR / "final_table_columns.csv", index=False, encoding="utf-8")
    summary = {
        "table": FINAL_TABLE_NAME,
        "row_count": int(len(final_table)),
        "column_count": int(len(final_table.columns)),
        "sum_reported_case_count": int(final_table["reported_case_count"].sum()),
        "diagnosis_count": int(final_table["diagnosis_code"].nunique()),
        "region_count": int(final_table["region_code"].nunique()),
        "age_group_count": int(final_table["age_group_code"].nunique()),
        "year_min": int(final_table["report_year"].min()),
        "year_max": int(final_table["report_year"].max()),
    }
    (DOCS_DIR / "final_table_summary.json").write_text(
        json.dumps(summary, ensure_ascii=False, indent=2) + "\n",
        encoding="utf-8",
    )


def register_table(con: duckdb.DuckDBPyConnection, name: str, frame: pd.DataFrame) -> None:
    con.register(f"df_{name}", frame)
    con.execute(f"CREATE OR REPLACE TABLE {name} AS SELECT * FROM df_{name}")
    con.unregister(f"df_{name}")


def register_final_fact_table(con: duckdb.DuckDBPyConnection, frame: pd.DataFrame) -> None:
    con.register("df_final_fact", frame)
    con.execute(
        f"""
        CREATE OR REPLACE TABLE {FINAL_TABLE_NAME} AS
        SELECT
          CAST(fact_id AS BIGINT) AS fact_id,
          CAST(source_dataset AS VARCHAR) AS source_dataset,
          CAST(source_row_id AS BIGINT) AS source_row_id,
          CAST(report_year AS INTEGER) AS report_year,
          CAST(report_month AS INTEGER) AS report_month,
          CAST(period_yyyymm AS INTEGER) AS period_yyyymm,
          CAST(date_grain AS VARCHAR) AS date_grain,
          CAST(region_code AS VARCHAR) AS region_code,
          CAST(region_name_cs AS VARCHAR) AS region_name_cs,
          CAST(diagnosis_code AS VARCHAR) AS diagnosis_code,
          CAST(diagnosis_name_cs AS VARCHAR) AS diagnosis_name_cs,
          CAST(mkn_code AS VARCHAR) AS mkn_code,
          CAST(mkn_code_with_dot AS VARCHAR) AS mkn_code_with_dot,
          CAST(mkn_name_cs AS VARCHAR) AS mkn_name_cs,
          CAST(mkn_iri AS VARCHAR) AS mkn_iri,
          CAST(mkn_block_code AS VARCHAR) AS mkn_block_code,
          CAST(mkn_block_name_cs AS VARCHAR) AS mkn_block_name_cs,
          CAST(mkn_block_source AS VARCHAR) AS mkn_block_source,
          CAST(mkn_chapter_range AS VARCHAR) AS mkn_chapter_range,
          CAST(mkn_chapter_number AS VARCHAR) AS mkn_chapter_number,
          CAST(mkn_chapter_name_cs AS VARCHAR) AS mkn_chapter_name_cs,
          CAST(has_mkn_match AS BOOLEAN) AS has_mkn_match,
          CAST(age_group_code AS VARCHAR) AS age_group_code,
          CAST(age_group_name_cs AS VARCHAR) AS age_group_name_cs,
          CAST(age_from_inclusive AS INTEGER) AS age_from_inclusive,
          CAST(age_to_inclusive AS INTEGER) AS age_to_inclusive,
          CAST(has_age_group_match AS BOOLEAN) AS has_age_group_match,
          CAST(sex_code AS VARCHAR) AS sex_code,
          CAST(sex_name_cs AS VARCHAR) AS sex_name_cs,
          CAST(ews_code AS INTEGER) AS ews_code,
          CAST(reported_case_count AS BIGINT) AS reported_case_count
        FROM df_final_fact
        """
    )
    con.unregister("df_final_fact")


def create_views_and_indexes(con: duckdb.DuckDBPyConnection) -> None:
    log("Creating compatibility view and indexes")
    con.execute(
        f"""
        CREATE OR REPLACE VIEW infectious_diseases AS
        SELECT
          report_year AS rok,
          report_month AS mesic,
          region_code AS kraj_kod,
          region_name_cs AS kraj_nazev,
          diagnosis_code AS diagnoza,
          diagnosis_name_cs AS diagnoza_nazev,
          age_group_code AS vek_kod,
          age_group_name_cs AS vek_nazev,
          sex_code AS pohlavi,
          ews_code AS EWS,
          reported_case_count AS pocet_pripadu
        FROM {FINAL_TABLE_NAME}
        """
    )
    for statement in [
        f"CREATE INDEX IF NOT EXISTS idx_fact_diag ON {FINAL_TABLE_NAME}(diagnosis_code)",
        f"CREATE INDEX IF NOT EXISTS idx_fact_block ON {FINAL_TABLE_NAME}(mkn_block_code)",
        f"CREATE INDEX IF NOT EXISTS idx_fact_year ON {FINAL_TABLE_NAME}(report_year)",
        f"CREATE INDEX IF NOT EXISTS idx_fact_region ON {FINAL_TABLE_NAME}(region_code)",
        f"CREATE INDEX IF NOT EXISTS idx_fact_age ON {FINAL_TABLE_NAME}(age_group_code)",
        f"CREATE INDEX IF NOT EXISTS idx_fact_block_year ON {FINAL_TABLE_NAME}(mkn_block_code, report_year)",
        f"CREATE INDEX IF NOT EXISTS idx_fact_diag_region ON {FINAL_TABLE_NAME}(diagnosis_code, region_code)",
    ]:
        con.execute(statement)
    con.execute("ANALYZE")


def create_database(db_path: Path, *, overwrite: bool) -> dict[str, Any]:
    db_path.parent.mkdir(parents=True, exist_ok=True)
    if db_path.exists() and overwrite:
        db_path.unlink()
    elif db_path.exists() and not overwrite:
        raise FileExistsError(f"{db_path} already exists; pass --overwrite to rebuild it.")

    data = read_csvs()
    dim_block = build_block_dimension()
    dim_mkn = build_mkn_dimension(data["mkn10"])
    dim_age = build_age_dimension(data["age_groups"])
    dim_region = build_region_dimension(data["infectious"])
    fact = build_final_fact(data["infectious"], dim_mkn, dim_age)
    kg_nodes = load_kg_nodes()
    kg_edges = load_kg_edges()
    eval_tables = load_evaluation_tables()
    write_docs(fact)

    log(f"Writing DuckDB database to {db_path.relative_to(ROOT)}")
    con = duckdb.connect(str(db_path))
    con.execute(f"PRAGMA threads={max(1, os.cpu_count() or 1)}")

    register_table(con, "source_infectious_diseases", data["infectious"])
    register_table(con, "source_age_groups", data["age_groups"])
    register_table(con, "source_mkn10_cz", data["mkn10"])
    register_table(con, "source_hospitalization", data["hospitalization"])
    register_table(con, "dim_mkn10_block", dim_block)
    register_table(con, "dim_mkn10_code", dim_mkn)
    register_table(con, "dim_age_group", dim_age)
    register_table(con, "dim_region", dim_region)
    register_final_fact_table(con, fact)
    register_table(con, "kg_node", kg_nodes)
    register_table(con, "kg_edge", kg_edges)
    register_table(con, "column_dictionary", pd.DataFrame(FINAL_TABLE_COLUMNS))
    for name, frame in eval_tables.items():
        register_table(con, name, frame)
    create_views_and_indexes(con)

    table_counts = {}
    for table_name in [
        "source_infectious_diseases",
        "source_age_groups",
        "source_mkn10_cz",
        "source_hospitalization",
        "dim_mkn10_block",
        "dim_mkn10_code",
        "dim_age_group",
        "dim_region",
        FINAL_TABLE_NAME,
        "kg_node",
        "kg_edge",
        "evaluation_question",
    ]:
        table_counts[table_name] = int(con.execute(f"SELECT COUNT(*) FROM {table_name}").fetchone()[0])
    con.close()

    manifest = {
        "generated_at": now_iso(),
        "database_path": str(db_path.relative_to(ROOT)),
        "database_bytes": db_path.stat().st_size,
        "duckdb_version": duckdb.__version__,
        "final_table": FINAL_TABLE_NAME,
        "final_table_rows": int(len(fact)),
        "final_table_columns": len(FINAL_TABLE_COLUMNS),
        "table_counts": table_counts,
        "source_files": {
            "infectious_diseases": {
                "path": "data/raw/infectious_diseases.csv",
                "sha256": file_sha256(RAW_DIR / "infectious_diseases.csv"),
            },
            "age_groups": {
                "path": "data/raw/age_groups.csv",
                "sha256": file_sha256(RAW_DIR / "age_groups.csv"),
            },
            "mkn10_cz": {
                "path": "data/raw/mkn10_cz.csv",
                "sha256": file_sha256(RAW_DIR / "mkn10_cz.csv"),
            },
            "hospitalization": {
                "path": "data/raw/hospitalization.csv",
                "sha256": file_sha256(RAW_DIR / "hospitalization.csv"),
            },
        },
        "notes": [
            "The final answer table is fact_infectious_disease_cases_enriched.",
            "Both standard RAG and KG-RAG should generate SQL against the same final table.",
            "KG-RAG's expected advantage is better scope construction before SQL, not a different fact table.",
        ],
    }
    (SQL_ROOT / "db_manifest.json").write_text(json.dumps(manifest, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    return manifest


def main() -> int:
    parser = argparse.ArgumentParser(description="Create the local DuckDB database for SQL answer generation.")
    parser.add_argument("--db", type=Path, default=DEFAULT_DB_PATH)
    parser.add_argument("--overwrite", action="store_true")
    args = parser.parse_args()

    manifest = create_database(args.db, overwrite=args.overwrite)
    print(
        f"Created {manifest['database_path']} with final table "
        f"{manifest['final_table']} ({manifest['final_table_rows']} rows)."
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
